using System.Globalization;
using System.Reflection;
using System.Resources;
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Fusion8.Cropper.Core.Resources
{
	/// <summary>
	/// Provides access to an assembly's string resources
	/// </summary>
	internal class ResourceFormatter
	{
		private static ResourceManager _resourceManager;

		private ResourceFormatter()
		{}

		/// <summary>
		/// ResourceManager property with lazy initialization
		/// </summary>
		/// <value>An instance of the ResourceManager class.</value>
		private static ResourceManager ResourceManager
		{
			get
			{
				if ((_resourceManager == null))
				{
					_resourceManager = new ResourceManager("Fusion8.Cropper.Core.Resources.Resources", Assembly.GetExecutingAssembly());
				}
				return _resourceManager;
			}
		}

		/// <summary>
		/// Loads an unformatted string
		/// </summary>
		/// <param name="resourceId">Identifier of string resource</param>
		/// <returns>string</returns>
		public static string GetString(string resourceId)
		{
			return ResourceManager.GetString(resourceId);
		}

		/// <summary>
		/// Loads a formatted string
		/// </summary>
		/// <param name="resourceId">Identifier of string resource</param>
		/// <param name="args">Array of objects to be passed to string.Format</param>
		/// <returns>string</returns>
		public static string GetString(string resourceId, object[] args)
		{
			string format = ResourceManager.GetString(resourceId);
			return string.Format(CultureInfo.CurrentCulture, format, args);
		}
	}

	/// <summary>
	/// Access to resource identifier ExConfigObjectNull
	/// </summary>
	internal class ExConfigObjectNull
	{
		private ExConfigObjectNull()
		{}

		public static string GetString()
		{
			return ResourceFormatter.GetString("ExConfigObjectNull");
		}
	}

	/// <summary>
	/// Access to resource identifier ExConfigPathNull
	/// </summary>
	internal class ExConfigPathNull
	{
		private ExConfigPathNull()
		{}

		public static string GetString()
		{
			return ResourceFormatter.GetString("ExConfigPathNull");
		}
	}

	/// <summary>
	/// Access to resource identifier ExImageFormatNull
	/// </summary>
	internal class ExImageFormatNull
	{
		private ExImageFormatNull()
		{}

		public static string GetString()
		{
			return ResourceFormatter.GetString("ExImageFormatNull");
		}
	}

	/// <summary>
	/// Access to resource identifier ExThumbnailSizeOutOfRange
	/// </summary>
	internal class ExThumbnailSizeOutOfRange
	{
		private ExThumbnailSizeOutOfRange()
		{}

		public static string GetString()
		{
			return ResourceFormatter.GetString("ExThumbnailSizeOutOfRange");
		}
	}
}