// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Brian Scott
//      Runtime version: 2.0.50727.312
// 
//      It contains classes defined from the contents of the resource file:
//        G:\Current\Cropper\src\Cropper\Resources\SR.resx
// 
//      Generated: Monday, February 19, 2007 4:39 AM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Fusion8.Cropper
{
    using System;
    
    
    internal class SR
    {
        
        public static string ExceptionCenterSizeOutOfRange
        {
            get
            {
                return Keys.GetString(Keys.ExceptionCenterSizeOutOfRange);
            }
        }
        
        public static string ExceptionUnhandled
        {
            get
            {
                return Keys.GetString(Keys.ExceptionUnhandled);
            }
        }
        
        public static string ExceptionUnhandledCaption
        {
            get
            {
                return Keys.GetString(Keys.ExceptionUnhandledCaption);
            }
        }
        
        public static string FolderBrowseText
        {
            get
            {
                return Keys.GetString(Keys.FolderBrowseText);
            }
        }
        
        public static string HomepageLinkUrl
        {
            get
            {
                return Keys.GetString(Keys.HomepageLinkUrl);
            }
        }
        
        public static string MenuAbout
        {
            get
            {
                return Keys.GetString(Keys.MenuAbout);
            }
        }
        
        public static string MenuBrowse
        {
            get
            {
                return Keys.GetString(Keys.MenuBrowse);
            }
        }
        
        public static string MenuExit
        {
            get
            {
                return Keys.GetString(Keys.MenuExit);
            }
        }
        
        public static string MenuHelp
        {
            get
            {
                return Keys.GetString(Keys.MenuHelp);
            }
        }
        
        public static string MenuHelpHowTo
        {
            get
            {
                return Keys.GetString(Keys.MenuHelpHowTo);
            }
        }
        
        public static string MenuHelpWeb
        {
            get
            {
                return Keys.GetString(Keys.MenuHelpWeb);
            }
        }
        
        public static string MenuHide
        {
            get
            {
                return Keys.GetString(Keys.MenuHide);
            }
        }
        
        public static string MenuInvert
        {
            get
            {
                return Keys.GetString(Keys.MenuInvert);
            }
        }
        
        public static string MenuOnTop
        {
            get
            {
                return Keys.GetString(Keys.MenuOnTop);
            }
        }
        
        public static string MenuOpacity
        {
            get
            {
                return Keys.GetString(Keys.MenuOpacity);
            }
        }
        
        public static string MenuOptions
        {
            get
            {
                return Keys.GetString(Keys.MenuOptions);
            }
        }
        
        public static string MenuOutput
        {
            get
            {
                return Keys.GetString(Keys.MenuOutput);
            }
        }
        
        public static string MenuReset
        {
            get
            {
                return Keys.GetString(Keys.MenuReset);
            }
        }
        
        public static string MenuSeperator
        {
            get
            {
                return Keys.GetString(Keys.MenuSeperator);
            }
        }
        
        public static string MenuShow
        {
            get
            {
                return Keys.GetString(Keys.MenuShow);
            }
        }
        
        public static string MenuSize
        {
            get
            {
                return Keys.GetString(Keys.MenuSize);
            }
        }
        
        public static string MenuThumbnail
        {
            get
            {
                return Keys.GetString(Keys.MenuThumbnail);
            }
        }
        
        public static string MenuUnknownCaption
        {
            get
            {
                return Keys.GetString(Keys.MenuUnknownCaption);
            }
        }
        
        public static string MenuUnknownText
        {
            get
            {
                return Keys.GetString(Keys.MenuUnknownText);
            }
        }
        
        public static string MessageAbout
        {
            get
            {
                return Keys.GetString(Keys.MessageAbout);
            }
        }
        
        public static string MessageHelp
        {
            get
            {
                return Keys.GetString(Keys.MessageHelp);
            }
        }
        
        public static string MessageInvalidPathCharacters
        {
            get
            {
                return Keys.GetString(Keys.MessageInvalidPathCharacters);
            }
        }
        
        public static string MessageInvalidTemplateCharacters
        {
            get
            {
                return Keys.GetString(Keys.MessageInvalidTemplateCharacters);
            }
        }
        
        public static string MessageNoOutputLoaded
        {
            get
            {
                return Keys.GetString(Keys.MessageNoOutputLoaded);
            }
        }
        
        public static string OptionFullImageTemplateLabelText
        {
            get
            {
                return Keys.GetString(Keys.OptionFullImageTemplateLabelText);
            }
        }
        
        public static string OptionHotKeysDescription
        {
            get
            {
                return Keys.GetString(Keys.OptionHotKeysDescription);
            }
        }
        
        public static string OptionNonRectWindowsDescription
        {
            get
            {
                return Keys.GetString(Keys.OptionNonRectWindowsDescription);
            }
        }
        
        public static string OptionOutputFolderGroupText
        {
            get
            {
                return Keys.GetString(Keys.OptionOutputFolderGroupText);
            }
        }
        
        public static string OptionOutputFolderLabelTemplate
        {
            get
            {
                return Keys.GetString(Keys.OptionOutputFolderLabelTemplate);
            }
        }
        
        public static string OptionOutputTemplateGroupText
        {
            get
            {
                return Keys.GetString(Keys.OptionOutputTemplateGroupText);
            }
        }
        
        public static string OptionOutputTemplatesDescription
        {
            get
            {
                return Keys.GetString(Keys.OptionOutputTemplatesDescription);
            }
        }
        
        public static string OptionThumbImageTemplateLabelText
        {
            get
            {
                return Keys.GetString(Keys.OptionThumbImageTemplateLabelText);
            }
        }
        
        public static string OptionVisibility
        {
            get
            {
                return Keys.GetString(Keys.OptionVisibility);
            }
        }
        
        private class Keys
        {
            
            static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Fusion8.Cropper.Resources.SR", typeof(SR).Assembly);
            
            public const string ExceptionCenterSizeOutOfRange = "ExceptionCenterSizeOutOfRange";
            
            public const string ExceptionUnhandled = "ExceptionUnhandled";
            
            public const string ExceptionUnhandledCaption = "ExceptionUnhandledCaption";
            
            public const string FolderBrowseText = "FolderBrowseText";
            
            public const string HomepageLinkUrl = "HomepageLinkUrl";
            
            public const string MenuAbout = "MenuAbout";
            
            public const string MenuBrowse = "MenuBrowse";
            
            public const string MenuExit = "MenuExit";
            
            public const string MenuHelp = "MenuHelp";
            
            public const string MenuHelpHowTo = "MenuHelpHowTo";
            
            public const string MenuHelpWeb = "MenuHelpWeb";
            
            public const string MenuHide = "MenuHide";
            
            public const string MenuInvert = "MenuInvert";
            
            public const string MenuOnTop = "MenuOnTop";
            
            public const string MenuOpacity = "MenuOpacity";
            
            public const string MenuOptions = "MenuOptions";
            
            public const string MenuOutput = "MenuOutput";
            
            public const string MenuReset = "MenuReset";
            
            public const string MenuSeperator = "MenuSeperator";
            
            public const string MenuShow = "MenuShow";
            
            public const string MenuSize = "MenuSize";
            
            public const string MenuThumbnail = "MenuThumbnail";
            
            public const string MenuUnknownCaption = "MenuUnknownCaption";
            
            public const string MenuUnknownText = "MenuUnknownText";
            
            public const string MessageAbout = "MessageAbout";
            
            public const string MessageHelp = "MessageHelp";
            
            public const string MessageInvalidPathCharacters = "MessageInvalidPathCharacters";
            
            public const string MessageInvalidTemplateCharacters = "MessageInvalidTemplateCharacters";
            
            public const string MessageNoOutputLoaded = "MessageNoOutputLoaded";
            
            public const string OptionFullImageTemplateLabelText = "OptionFullImageTemplateLabelText";
            
            public const string OptionHotKeysDescription = "OptionHotKeysDescription";
            
            public const string OptionNonRectWindowsDescription = "OptionNonRectWindowsDescription";
            
            public const string OptionOutputFolderGroupText = "OptionOutputFolderGroupText";
            
            public const string OptionOutputFolderLabelTemplate = "OptionOutputFolderLabelTemplate";
            
            public const string OptionOutputTemplateGroupText = "OptionOutputTemplateGroupText";
            
            public const string OptionOutputTemplatesDescription = "OptionOutputTemplatesDescription";
            
            public const string OptionThumbImageTemplateLabelText = "OptionThumbImageTemplateLabelText";
            
            public const string OptionVisibility = "OptionVisibility";
            
            public static string GetString(string key)
            {
                return resourceManager.GetString(key, Resources.CultureInfo);
            }
            
            public static string GetString(string key, object[] args)
            {
                string msg = resourceManager.GetString(key, Resources.CultureInfo);
                msg = string.Format(msg, args);
                return msg;
            }
        }
    }
}
